# Generated by Django 3.2 on 2021-04-10 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['name'], 'verbose_name': 'Port', 'verbose_name_plural': 'Ports'},
        ),
        migrations.AlterModelOptions(
            name='timezone',
            options={'ordering': ['name'], 'verbose_name': 'Time Zone', 'verbose_name_plural': 'Time Zones'},
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('country_of_registry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.country')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['name'],
            },
        ),
    ]
