# Generated by Django 3.2 on 2021-04-11 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20210411_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='country_of_registry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.country'),
        ),
    ]
