# Generated by Django 3.2 on 2021-04-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_contactdetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AgentCargo',
                'verbose_name_plural': 'AgentCargos',
            },
        ),
        migrations.CreateModel(
            name='AgentVesselType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AgentVesselType',
                'verbose_name_plural': 'AgentVesselType',
            },
        ),
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'ordering': ['port'], 'verbose_name': 'Contact Detail', 'verbose_name_plural': 'Contact Details'},
        ),
        migrations.AddField(
            model_name='agent',
            name='appointments',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
