# Generated by Django 3.2 on 2021-04-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_delete_agentcargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AgentCargo',
                'verbose_name_plural': 'AgentCargos',
            },
        ),
    ]
