# Generated by Django 3.2 on 2021-04-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentcargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentCargo',
        ),
        migrations.DeleteModel(
            name='AgentVesselType',
        ),
        migrations.AddField(
            model_name='agent',
            name='discharging_activity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='loading_activity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
