# Generated by Django 3.2 on 2021-04-20 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_auto_20210421_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVesselType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveSmallIntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
            ],
            options={
                'verbose_name': 'AgentVesselType',
                'verbose_name_plural': 'AgentVesselType',
                'ordering': ['agent__name'],
            },
        ),
        migrations.CreateModel(
            name='AgentCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveSmallIntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
            ],
            options={
                'verbose_name': 'AgentCargo',
                'verbose_name_plural': 'AgentCargos',
                'ordering': ['agent__name'],
            },
        ),
    ]
